#!/bin/bash
#SBATCH --job-name=paper-mnist-sweep
#SBATCH --partition=gpu_a100_il
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=16gb
#SBATCH --time=08:00:00
#SBATCH --output=job_%j.out
#SBATCH --error=job_%j.err

module load compiler/gnu/14.2
module load devel/python/3.11.7-gnu-14.2
module load devel/cuda/12.8

if [ ! -d ~/myenv ]; then
    python -m venv ~/myenv
fi
source ~/myenv/bin/activate

cd "$HOME/PaTAS"
REPO=PaTAS-Subjective-Logic-Neural-Networks-Trust-Assessment

# Regenerates the paper's Experiment 2 (MNIST width sweep, Table II):
# vacuous/vacuous at widths 16/32/64/128 + two-layer 16-16, and trust/trust
# at 16 (+16-16).  test_mnist.py has no --force flag, so the legacy caches
# are archived first.  Patterns are pinned to the sweep widths AND
# PathSize_None, so neither the UQ battery (mnist_512*, gtsrb_*) nor the
# poisoned experiment's PathSize_<digit> dirs (regenerated by the
# paper-cancer-pois job, possibly running concurrently) are touched.
ARCHIVE="results/OLD_legacy_${SLURM_JOB_ID}"
mkdir -p "$ARCHIVE"
for h in 16 32 64 128 16_16; do
    for d in results/NN_Train_mnist_${h}_*_PathSize_None* \
             results/PTAS_Eval_mnist_${h}_*_PathSize_None*; do
        [ -d "$d" ] && mv "$d" "$ARCHIVE/"
    done
done

python $REPO/tests/test_mnist.py
